package softwarearchitektur.mailverwaltung;

public class MailTemplate {
    public static String mailTemplate = "    <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
            + "    <html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"
            + "    <head>\r\n"
            + "      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n"
            + "      <title>[SUBJECT]</title>\r\n"
            + "      <style type=\"text/css\">\r\n"
            + "      body {\r\n"
            + "       padding-top: 0 !important;\r\n"
            + "       padding-bottom: 0 !important;\r\n"
            + "       padding-top: 0 !important;\r\n"
            + "       padding-bottom: 0 !important;\r\n"
            + "       margin:0 !important;\r\n"
            + "       width: 100% !important;\r\n"
            + "       -webkit-text-size-adjust: 100% !important;\r\n"
            + "       -ms-text-size-adjust: 100% !important;\r\n"
            + "       -webkit-font-smoothing: antialiased !important;\r\n"
            + "     }\r\n"
            + "     .tableContent img {\r\n"
            + "       border: 0 !important;\r\n"
            + "       display: block !important;\r\n"
            + "       outline: none !important;\r\n"
            + "     }\r\n"
            + "     a{\r\n"
            + "      color:#382F2E;\r\n"
            + "    }\r\n"
            + "\r\n"
            + "    p, h1{\r\n"
            + "      color:#382F2E;\r\n"
            + "      margin:0;\r\n"
            + "    }\r\n"
            + " p{\r\n"
            + "      text-align:left;\r\n"
            + "      color:#999999;\r\n"
            + "      font-size:14px;\r\n"
            + "      font-weight:normal;\r\n"
            + "      line-height:19px;\r\n"
            + "    }\r\n"
            + "\r\n"
            + "    a.link1{\r\n"
            + "      color:#382F2E;\r\n"
            + "    }\r\n"
            + "    a.link2{\r\n"
            + "      font-size:16px;\r\n"
            + "      text-decoration:none;\r\n"
            + "      color:#ffffff;\r\n"
            + "    }\r\n"
            + "\r\n"
            + "    h2{\r\n"
            + "      text-align:left;\r\n"
            + "       color:#222222; \r\n"
            + "       font-size:19px;\r\n"
            + "      font-weight:normal;\r\n"
            + "    }\r\n"
            + "    div,p,ul,h1{\r\n"
            + "      margin:0;\r\n"
            + "    }\r\n"
            + "\r\n"
            + "    .bgBody{\r\n"
            + "      background: #ffffff;\r\n"
            + "    }\r\n"
            + "    .bgItem{\r\n"
            + "      background: #ffffff;\r\n"
            + "    }\r\n"
            + "	\r\n"
            + "@media only screen and (max-width:480px)\r\n"
            + "		\r\n"
            + "{\r\n"
            + "		\r\n"
            + "table[class=\"MainContainer\"], td[class=\"cell\"] \r\n"
            + "	{\r\n"
            + "		width: 100% !important;\r\n"
            + "		height:auto !important; \r\n"
            + "	}\r\n"
            + "td[class=\"specbundle\"] \r\n"
            + "	{\r\n"
            + "		width:100% !important;\r\n"
            + "		float:left !important;\r\n"
            + "		font-size:13px !important;\r\n"
            + "		line-height:17px !important;\r\n"
            + "		display:block !important;\r\n"
            + "		padding-bottom:15px !important;\r\n"
            + "	}\r\n"
            + "		\r\n"
            + "td[class=\"spechide\"] \r\n"
            + "	{\r\n"
            + "		display:none !important;\r\n"
            + "	}\r\n"
            + "	    img[class=\"banner\"] \r\n"
            + "	{\r\n"
            + "	          width: 100% !important;\r\n"
            + "	          height: auto !important;\r\n"
            + "	}\r\n"
            + "		td[class=\"left_pad\"] \r\n"
            + "	{\r\n"
            + "			padding-left:15px !important;\r\n"
            + "			padding-right:15px !important;\r\n"
            + "	}\r\n"
            + "		 \r\n"
            + "}\r\n"
            + "	\r\n"
            + "@media only screen and (max-width:540px) \r\n"
            + "\r\n"
            + "{\r\n"
            + "		\r\n"
            + "table[class=\"MainContainer\"], td[class=\"cell\"] \r\n"
            + "	{\r\n"
            + "		width: 100% !important;\r\n"
            + "		height:auto !important; \r\n"
            + "	}\r\n"
            + "td[class=\"specbundle\"] \r\n"
            + "	{\r\n"
            + "		width:100% !important;\r\n"
            + "		float:left !important;\r\n"
            + "		font-size:13px !important;\r\n"
            + "		line-height:17px !important;\r\n"
            + "		display:block !important;\r\n"
            + "		padding-bottom:15px !important;\r\n"
            + "	}\r\n"
            + "		\r\n"
            + "td[class=\"spechide\"] \r\n"
            + "	{\r\n"
            + "		display:none !important;\r\n"
            + "	}\r\n"
            + "	    img[class=\"banner\"] \r\n"
            + "	{\r\n"
            + "	          width: 100% !important;\r\n"
            + "	          height: auto !important;\r\n"
            + "	}\r\n"
            + "	.font {\r\n"
            + "		font-size:18px !important;\r\n"
            + "		line-height:22px !important;\r\n"
            + "		\r\n"
            + "		}\r\n"
            + "		.font1 {\r\n"
            + "		font-size:18px !important;\r\n"
            + "		line-height:22px !important;\r\n"
            + "		\r\n"
            + "		}\r\n"
            + "}\r\n"
            + "\r\n"
            + "    </style>\r\n"
            + "<script type=\"colorScheme\" class=\"swatch active\">\r\n"
            + "{\r\n"
            + "    \"name\":\"Default\",\r\n"
            + "    \"bgBody\":\"ffffff\",\r\n"
            + "    \"link\":\"382F2E\",\r\n"
            + "    \"color\":\"999999\",\r\n"
            + "    \"bgItem\":\"ffffff\",\r\n"
            + "    \"title\":\"222222\"\r\n"
            + "}\r\n"
            + "</script>\r\n"
            + "  </head>\r\n"
            + "  <body paddingwidth=\"0\" paddingheight=\"0\"   style=\"padding-top: 0; padding-bottom: 0; padding-top: 0; padding-bottom: 0; background-repeat: repeat; width: 100% !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-font-smoothing: antialiased;\" offset=\"0\" toppadding=\"0\" leftpadding=\"0\">\r\n"
            + "    <table bgcolor=\"#ffffff\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"tableContent\" align=\"center\"  style='font-family:Helvetica, Arial,serif;'>\r\n"
            + "  <tbody>\r\n"
            + "    <tr>\r\n"
            + "      <td><table width=\"600\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" bgcolor=\"#ffffff\" class=\"MainContainer\">\r\n"
            + "  <tbody>\r\n"
            + "    <tr>\r\n"
            + "      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
            + "  <tbody>\r\n"
            + "    <tr>\r\n"
            + "      <td valign=\"top\" width=\"40\">&nbsp;</td>\r\n"
            + "      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
            + "  <tbody>\r\n"
            + "  <!-- =============================== Header ====================================== -->   \r\n"
            + "    <tr>\r\n"
            + "    	<td height='75' class=\"spechide\"></td>\r\n"
            + "        \r\n"
            + "        <!-- =============================== Body ====================================== -->\r\n"
            + "    </tr>\r\n"
            + "    <tr>\r\n"
            + "      <td class='movableContentContainer ' valign='top'>\r\n"
            + "      	<div class=\"movableContent\" style=\"border: 0px; padding-top: 0px; position: relative;\">\r\n"
            + "        	<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
            + "  <tbody>\r\n"
            + "    <tr>\r\n"
            + "      <td height=\"35\"></td>\r\n"
            + "    </tr>\r\n"
            + "    <tr>\r\n"
            + "      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
            + "</table>\r\n"
            + "</td>\r\n"
            + "    </tr>\r\n"
            + "  </tbody>\r\n"
            + "</table>\r\n"
            + "        </div>\r\n"
            + "        <div class=\"movableContent\" style=\"border: 0px; padding-top: 0px; position: relative;\">\r\n"
            + "        	<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
            + "                          <tr>\r\n"
            + "                            <td valign='top' align='center'>\r\n"
            + "                              <div class=\"contentEditableContainer contentImageEditable\">\r\n"
            + "                                <div class=\"contentEditable\">\r\n"
            + "                                  <img src=\"https://res.cloudinary.com/herrleel/image/upload/v1647176902/Logo_d3o5dx.png\" width='251' height='150' alt='' data-default=\"placeholder\" data-max-width=\"560\">\r\n"
            + "                                </div>\r\n"
            + "                              </div>\r\n"
            + "                            </td>\r\n"
            + "                          </tr>\r\n"
            + "                        </table>\r\n"
            + "        </div>\r\n"
            + "        <div class=\"movableContent\" style=\"border: 0px; padding-top: 0px; position: relative;\">\r\n"
            + "        	<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
            + "                          <tr><td height='55'></td></tr>\r\n"
            + "                          <tr>\r\n"
            + "                            <td align='left'>\r\n"
            + "                              <div class=\"contentEditableContainer contentTextEditable\">\r\n"
            + "                                <div class=\"contentEditable\" align='center'>\r\n"
            + "                                  <h2 >Guten Tag!</h2>\r\n"
            + "                                </div>\r\n"
            + "                              </div>\r\n"
            + "                            </td>\r\n"
            + "                          </tr>\r\n"
            + "\r\n"
            + "                          <tr><td height='15'> </td></tr>\r\n"
            + "\r\n"
            + "                          <tr>\r\n"
            + "                            <td align='left'>\r\n"
            + "                              <div class=\"contentEditableContainer contentTextEditable\">\r\n"
            + "                                <div class=\"contentEditable\" align='center'>\r\n"
            + "                                  <p >\r\n"
            + "                                    <#content>\r\n"
            + "                                    <br>\r\n"
            + "                                    <br>\r\n"
            + "                                    Sie haben weitere Fragen? Erreichen Sie uns über Facebook und Twitter oder schreiben Sie unserem Support-Team\r\n"
            + "                                    <br>\r\n"
            + "                                    <br>\r\n"
            + "                                    Viele Grüße,\r\n"
            + "                                    <br>\r\n"
            + "                                    <span style='color:#222222;'>Ihr Leihdienst</span>\r\n"
            + "                                  </p>\r\n"
            + "                                </div>\r\n"
            + "                              </div>\r\n"
            + "                            </td>\r\n"
            + "                          </tr>\r\n"
            + "\r\n"
            + "                          <tr><td height='55'></td></tr>\r\n"
            + "                        </table>\r\n"
            + "        </div>\r\n"
            + "        <div class=\"movableContent\" style=\"border: 0px; padding-top: 0px; position: relative;\">\r\n"
            + "        	<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
            + "  <tbody>\r\n"
            + "    <tr>\r\n"
            + "      <td height='65'>\r\n"
            + "    </tr>\r\n"
            + "    <tr>\r\n"
            + "      <td  style='border-bottom:1px solid #DDDDDD;'></td>\r\n"
            + "    </tr>\r\n"
            + "    <tr><td height='25'></td></tr>\r\n"
            + "    <tr>\r\n"
            + "      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
            + "  <tbody>\r\n"
            + "    <tr>\r\n"
            + "      <td valign=\"top\" class=\"specbundle\"><div class=\"contentEditableContainer contentTextEditable\">\r\n"
            + "                                      <div class=\"contentEditable\" align='center'>\r\n"
            + "                                        <p  style='text-align:left;color:#CCCCCC;font-size:12px;font-weight:normal;line-height:20px;'>\r\n"
            + "                                          <span style='font-weight:bold;'>Leihdienst</span>\r\n"
            + "                                          <br>\r\n"
            + "                                          Leihdienst-Adresse\r\n"
            + "                                          <br>\r\n"
            + "                                          <a target='_blank' href=\"[FORWARD]\">Forward to a friend</a><br>\r\n"
            + "                                          <a target=\"_blank\" class='link1' class='color:#382F2E;' href=\"[UNSUBSCRIBE]\">Unsubscribe</a>\r\n"
            + "                                          <br>\r\n"
            + "                                          <a target='_blank' class='link1' class='color:#382F2E;' href=\"[SHOWEMAIL]\">Show this email in your browser</a>\r\n"
            + "                                        </p>\r\n"
            + "                                      </div>\r\n"
            + "                                    </div></td>\r\n"
            + "      <td valign=\"top\" width=\"30\" class=\"specbundle\">&nbsp;</td>\r\n"
            + "      <td valign=\"top\" class=\"specbundle\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
            + "  <tbody>\r\n"
            + "    <tr>\r\n"
            + "      <td valign='top' width='52'>\r\n"
            + "                                    <div class=\"contentEditableContainer contentFacebookEditable\">\r\n"
            + "                                      <div class=\"contentEditable\">\r\n"
            + "                                        <a target='_blank' href=\"#\"><img src=\"https://res.cloudinary.com/herrleel/image/upload/v1647177507/facebook_e9zhoj.png\" width='52' height='53' alt='facebook icon' data-default=\"placeholder\" data-max-width=\"52\" data-customIcon=\"true\"></a>\r\n"
            + "                                      </div>\r\n"
            + "                                    </div>\r\n"
            + "                                  </td>\r\n"
            + "      <td valign=\"top\" width=\"16\">&nbsp;</td>\r\n"
            + "      <td valign='top' width='52'>\r\n"
            + "                                    <div class=\"contentEditableContainer contentTwitterEditable\">\r\n"
            + "                                      <div class=\"contentEditable\">\r\n"
            + "                                        <a target='_blank' href=\"#\"><img src=\"https://res.cloudinary.com/herrleel/image/upload/v1647177514/twitter_oetepl.png\" width='52' height='53' alt='twitter icon' data-default=\"placeholder\" data-max-width=\"52\" data-customIcon=\"true\"></a>\r\n"
            + "                                      </div>\r\n"
            + "                                    </div>\r\n"
            + "                                  </td>\r\n"
            + "    </tr>\r\n"
            + "  </tbody>\r\n"
            + "</table>\r\n"
            + "</td>\r\n"
            + "    </tr>\r\n"
            + "  </tbody>\r\n"
            + "</table>\r\n"
            + "</td>\r\n"
            + "    </tr>\r\n"
            + "    <tr><td height='88'></td></tr>\r\n"
            + "  </tbody>\r\n"
            + "</table>\r\n"
            + "\r\n"
            + "        </div>\r\n"
            + "        \r\n"
            + "        <!-- =============================== footer ====================================== -->\r\n"
            + "      \r\n"
            + "      </td>\r\n"
            + "    </tr>\r\n"
            + "  </tbody>\r\n"
            + "</table>\r\n"
            + "</td>\r\n"
            + "      <td valign=\"top\" width=\"40\">&nbsp;</td>\r\n"
            + "    </tr>\r\n"
            + "  </tbody>\r\n"
            + "</table>\r\n"
            + "</td>\r\n"
            + "    </tr>\r\n"
            + "  </tbody>\r\n"
            + "</table>\r\n"
            + "</td>\r\n"
            + "    </tr>\r\n"
            + "  </tbody>\r\n"
            + "</table>\r\n"
            + "\r\n"
            + "\r\n"
            + "      </body>\r\n"
            + "      </html>\r\n"
            + "";
}

